import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Import Dataset
file = pd.read_csv('Transfers-2000-2018.csv')
# Initial Exploration
file.fillna(0)
print(file.head())
print(file.info())
print(file.shape)
print(file.columns)
print(file.describe())
# How does age affect a players value?
player_age = file.sort_values(["Age", "Transfer_fee"], ascending=[True, False])
player_age_value = player_age[["Name", "Age", "Transfer_fee"]]
print(player_age_value.head())
# Drop the first value, error
player_age_value = player_age_value.drop(labels=236, axis=0)
fee_by_age = player_age_value.groupby("Age")["Transfer_fee"].agg(np.sum)
print(fee_by_age)
fig, ax = plt.subplots()
ax.hist(player_age_value["Age"], bins=21)
ax.set_xlabel("Player Age")
ax.set_ylabel("Billions GBP")
ax.set_title("Sum Cost of Player per Age Group")
plt.show()
# Effect a player's position has on his value
positions = file.sort_values(["Position", "Transfer_fee"], ascending=[True, False])
print(positions.head())
fee_by_position = positions.pivot_table(values="Transfer_fee", index="Position", aggfunc=np.sum)
fee_by_position = fee_by_position.sort_index()
fig, ax = plt.subplots()
ax.bar(fee_by_position.index, fee_by_position["Transfer_fee"])
ax.set_xticklabels(fee_by_position.index, rotation=90)
ax.set_ylabel("Billions GBP")
ax.set_title("Sum of Transfer Fee by Position")
plt.show()
# Do attributes play a role?
pos_index = positions.set_index("Position")
attack = pos_index.loc[['Attacking Midfield', 'Centre-Forward', 'Forward', 'Left Winger', 'Right Winger', 'Second Striker']]
Midfield = pos_index.loc[['Central Midfield', 'Defensive Midfield', 'Left Midfield', 'Midfielder', 'Right Midfield']]
Defense = pos_index.loc[['Centre-Back', 'Defender', 'Left-Back', 'Right-Back', 'Sweeper', 'Goalkeeper']]
attack_sum_fee = attack.pivot_table("Transfer_fee", index="Season", aggfunc=np.sum)
mid_sum_fee = Midfield.pivot_table("Transfer_fee", index="Season", aggfunc=np.sum)
defense_sum_fee = Defense.pivot_table("Transfer_fee", index="Season", aggfunc=np.sum)
fig, ax = plt.subplots()
ax.plot(attack_sum_fee.index, attack_sum_fee["Transfer_fee"], marker="o")
ax.plot(mid_sum_fee.index, mid_sum_fee["Transfer_fee"], marker="o")
ax.plot(defense_sum_fee.index, defense_sum_fee["Transfer_fee"], marker="o")
ax.set_xlabel("Season (year - year)")
ax.set_ylabel("Billions GBP")
ax.set_title("Sum of Transfer Fees spent on Player Types")
ax.set_xticklabels(mid_sum_fee.index, rotation=90)
ax.legend(["Attack", "Midfield", "Defense"])
plt.show()
# What about the mean?
attack_avg_fee = attack.pivot_table("Transfer_fee", index="Season", aggfunc=np.mean)
mid_avg_fee = Midfield.pivot_table("Transfer_fee", index="Season", aggfunc=np.mean)
defense_avg_fee = Defense.pivot_table("Transfer_fee", index="Season", aggfunc=np.mean)
fig, ax = plt.subplots()
ax.plot(attack_avg_fee.index, attack_avg_fee["Transfer_fee"], marker="o")
ax.plot(mid_avg_fee.index, mid_avg_fee["Transfer_fee"], marker="o")
ax.plot(defense_avg_fee.index, defense_avg_fee["Transfer_fee"], marker="o")
ax.set_xlabel("Season (year - year)")
ax.set_ylabel("Billions GBP")
ax.set_title("Average Transfer Fees Spent on Player Types")
ax.set_xticklabels(mid_avg_fee.index, rotation=90)
ax.legend(["Attack", "Midfield", "Defense"])
plt.show()
# Which leagues are the most powerful?
leagues = file.pivot_table(values="Transfer_fee", index="League_to", aggfunc=(np.sum))
leagues = leagues.sort_values('Transfer_fee', ascending=False)
top15 = leagues.head(15)
fig, ax = plt.subplots()
ax.bar(top15.index, top15["Transfer_fee"])
ax.set_ylabel("Leagues")
ax.set_xlabel("Billions GBP")
ax.set_title("Highest Spending Football Leagues")
ax.set_xticklabels(top15.index, rotation=90)
plt.show()
top5 = leagues[:5]
world = leagues[5:]
print(top5.describe())
print(world.describe())
sum_fee_top5 = top5["Transfer_fee"].sum()
sum_fee_world = world["Transfer_fee"].sum()
dict = {"Leagues":["Top 5", "Rest of World"],"Sum Transfer Fee":[sum_fee_top5, sum_fee_world]}
global_comparison = pd.DataFrame(dict)
global_comparison = global_comparison.set_index("Leagues")
print(global_comparison)
print(top5)
fig, ax = plt.subplots()
ax.bar(global_comparison.index, global_comparison["Sum Transfer Fee"])
ax.set_xlabel("Leagues")
ax.set_ylabel("Billion GBP")
ax.set_title("Top 5 Spending Leagues v the rest")
plt.show()
# Premier League trend over time
leagues = file.set_index("League_to")
epl = leagues.loc[["Premier League"]]
epl_avg_fee = epl.pivot_table("Transfer_fee", index="Season", aggfunc=np.mean)
fig, ax = plt.subplots()
ax.plot(epl_avg_fee.index, epl_avg_fee["Transfer_fee"], marker="o")
ax.set_xlabel("Season")
ax.set_ylabel("Billions GBP")
ax.set_title("Average Premier League Transfer Fee per Season")
ax.set_xticklabels(epl_avg_fee.index, rotation=90)
ax.legend("Premier League")
plt.show()